version: "3.3"
services:
  binotify-premium-app:
    build: .
    image: binotify-premium-app:latest
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./index.html:/usr/src/app/index.html
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./postcss.config.cjs:/usr/src/app/postcss.config.cjs
      - ./tailwind.config.cjs:/usr/src/app/tailwind.config.cjs

    ports:
      - ${BINOTIFY_PREMIUM_APP_PORT:-5173}:${BINOTIFY_PREMIUM_APP_PORT:-5173}
    environment:
      - CHOKIDAR_USEPOLLING=true
